# load required packages ----
library(tximeta)
library(SummarizedExperiment)
library(DESeq2)
library(org.Hs.eg.db)

# create a pointer to salmon_quant files (salmon_quant directory generated by salmon.sh script) ----
files <- file.path(list.dirs("salmon_quant", full.names = T, recursive = F), "quant.sf")
file.exists(files)

# write sample information ----

coldata <- data.frame(files, names = c("SRR12345", "SRR12346"), condition = c("WT", "KO")) # This is an example. I have to update colData information based on the experiment. In general there will be multiple biological replicates.

# build se object ----

se <- tximeta(coldata)

# summarize counts at the gene-level ---- 

gse <- summarizeToGene(se)

# let's have a look at the structure of gse object----

assay(gse)

colData(gse)

assayNames(gse)

# Since we are plotting gene_ids in volcano plot, I'm adding gene_ids here

gse <- addIds(gse, "REFSEQ", gene = TRUE)
