# load required packages ----
library(tximeta)
library(SummarizedExperiment)
library(DESeq2)
library(org.Hs.eg.db)

# created a pointer to salmon_quant files (salmon_quant directory was generated by salmon.sh script) ----
files <- file.path("salmon_quant", c("SRR12345", "SRR12346), "quant.sf")

file.exists(files)

# write a matrix to build se object ----

coldata <- data.frame(files, names = c("SRR12345", "SRR12346") condition = c("WT", "KO") 

# build se object ----

se <- tximeta(coldata)

# summarize counts at the gene-level ---- 

gse <- summarizeToGene(se)

# have a look at the structure of gse object----

assay(gse)

colData(gse)

assayNames(gse)

# Since we need to label gene IDs in the volcano plot later, I'm going to add gene IDs.

gse <- addIds(gse, "REFSEQ", gene = TRUE)
